<%@ Page Title="" Language="C#" MasterPageFile="~/Views/Shared/Builder.Master" Inherits="System.Web.Mvc.ViewPage<Fluqi.Models.TabModel>" %>
<%@ Import Namespace="Fluqi.Web.Demo.Helpers" %>

<asp:Content ID="Content1" ContentPlaceHolderID="DemoMainContent" runat="server">
	<script src="<%=Url.Content("~/Scripts/tabs.js")%>" type="text/javascript"></script>
	<script src="<%=Url.Content("~/Scripts/jquery-ui-tabs-rotate.js")%>" type="text/javascript"></script>
<%
	var tabs = Html.CreateTabs("tabs");

	this.Model.ConfigureTabs(tabs);
	
	using (tabs.RenderHeader()) { %>

		<%using (tabs.Panes.RenderNextPane()) {%>
			<p>
				Proin elit arcu, rutrum commodo, vehicula tempus, commodo a, risus. Curabitur nec arcu. Donec 
				sollicitudin mi sit amet mauris. Nam elementum quam ullamcorper ante. Etiam aliquet massa et 
				lorem. Mauris dapibus lacus auctor risus. Aenean tempor ullamcorper leo. Vivamus sed magna 
				quis ligula eleifend adipiscing. Duis orci. Aliquam sodales tortor vitae ipsum. Aliquam nulla. 
				Duis aliquam molestie erat. Ut et mauris vel pede varius sollicitudin. Sed ut dolor nec orci 
				tincidunt interdum. Phasellus ipsum. Nunc tristique tempus lectus.
			</p>
		<%} %>
		
		<%using (tabs.Panes.RenderNextPane()) {%>
			<p>
				Morbi tincidunt, dui sit amet facilisis feugiat, odio metus gravida ante, ut pharetra massa 
				metus id nunc. Duis scelerisque molestie turpis. Sed fringilla, massa eget luctus malesuada, 
				metus eros molestie lectus, ut tempus eros massa ut dolor. Aenean aliquet fringilla sem. 
				Suspendisse sed ligula in ligula suscipit aliquam. Praesent in eros vestibulum mi adipiscing 
				adipiscing. Morbi facilisis. Curabitur ornare consequat nunc. Aenean vel metus. Ut posuere 
				viverra nulla. Aliquam erat volutpat. Pellentesque convallis. Maecenas feugiat, tellus 
				pellentesque pretium posuere, felis lorem euismod felis, eu ornare leo nisi vel felis. 
				Mauris consectetur tortor et purus.
			</p>
		<%} %>

		<%using (tabs.Panes.RenderNextPane()) {%>
			<p>
				Mauris eleifend est et turpis. Duis id erat. Suspendisse potenti. Aliquam vulputate, pede vel vehicula accumsan, 
				mi neque rutrum erat, eu congue orci lorem eget lorem. Vestibulum non ante. Class aptent taciti sociosqu 
				ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce sodales. Quisque eu urna vel enim 
				commodo pellentesque. Praesent eu risus hendrerit ligula tempus pretium. Curabitur lorem enim, pretium nec, 
				feugiat nec, luctus a, lacus.
			</p>
			<p>
				Duis cursus. Maecenas ligula eros, blandit nec, pharetra at, semper at, magna. Nullam ac lacus. Nulla 
				facilisi. Praesent viverra justo vitae neque. Praesent blandit adipiscing velit. Suspendisse potenti. 
				Donec mattis, pede vel pharetra blandit, magna ligula faucibus eros, id euismod lacus dolor eget odio. 
				Nam scelerisque. 
			</p>
		<%} %>
	 
	<%} // using(tabs.RenderHeader) %>

</asp:Content>



<asp:Content ID="Content2" ContentPlaceHolderID="DemoExampleContent" runat="server">
<%using (Html.BeginForm("Tabs", "Builder")) {%>
	<input type="submit" value="UPDATE" />
	<ul>
		<li><%=Html.LabelFor(vm=>vm.collapsible) %><%=Html.CheckBoxFor(vm=>vm.collapsible, "Tabs can collapse (a little like the accordion collapses).")%></li>
		<li><%=Html.LabelFor(vm=>vm.disabled)    %><%=Html.CheckBoxFor(vm=>vm.disabled, "Disables all the tabs in the control.")%></li>
		<li>
			<strong>Note that effects can have an impact on how the widget behaves.</strong><br />
			<%=Html.LabelFor(vm=>vm.showEffect)  %><%=Html.DropDownTipListFor(vm=>vm.showEffect, List.AnimationItems(), "Animation effect when showing a tab")%>
		</li>
		<li><%=Html.LabelFor(vm=>vm.showDuration)%><%=Html.TextBoxFor(vm=>vm.showDuration, "Duration of the show effect (numeric or 'slow', 'fast', etc).")%></li>
		<li><%=Html.LabelFor(vm=>vm.hideEffect)  %><%=Html.DropDownTipListFor(vm=>vm.hideEffect, List.AnimationItems(), "Animation effect when hiding a tab")%></li>
		<li><%=Html.LabelFor(vm=>vm.hideDuration)%><%=Html.TextBoxFor(vm=>vm.hideDuration, "Duration of the hide effect (numeric or 'slow', 'fast', etc).")%></li>
		<li><%=Html.LabelFor(vm=>vm.evt)         %><%=Html.DropDownTipListFor(vm=>vm.evt, List.BrowserEventItems(), "Event that causes the tabs to change, for example select 'mouseover'.")%></li>
		<li><%=Html.LabelFor(vm=>vm.selectedTab) %><%=Html.TextBoxFor(vm=>vm.selectedTab, "Select between 0 and 2 to select that tab on page load.")%></li>
	</ul>

	<hr />
	<h2>Test Harness Options</h2>
	<ul>
		<li><%=Html.LabelFor(vm=>vm.showEvents)    %><%=Html.CheckBoxFor(vm=>vm.showEvents, "Shows how events are wired up.")%></li>
		<li><%=Html.LabelFor(vm=>vm.renderCSS)     %><%=Html.CheckBoxFor(vm=>vm.renderCSS, "Shows the CSS generated by jQuery UI (so non-JavaScript users still see the layout/colours).")%></li>
		<li><%=Html.LabelFor(vm=>vm.prettyRender)  %><%=Html.CheckBoxFor(vm=>vm.prettyRender, "Shows the rendered control/JavaScript in a readable layout.  Turn this option off to see the compressed version (which is the default in a RELEASE build).")%></li>
	</ul>
	<input type="submit" value="UPDATE" />
<%}//form%>
</asp:Content>



<asp:Content ID="Content3" ContentPlaceHolderID="DemoCodeContent" runat="server">
<%
	var tabs = Html.CreateTabs("tabs");
	this.Model.ConfigureTabs(tabs);
%>	
<%=this.Model.CSharpCode(tabs)%>
</asp:Content>



<asp:Content ID="Content4" ContentPlaceHolderID="DemoHtmlContent" runat="server">
<%
	var tabs = Html.CreateTabs("tabs");
	this.Model.ConfigureTabs(tabs);
	tabs
		.Rendering
			// SetAutoScript off as we want to show the JavaScript separately
			.SetAutoScript(false)
		.Finish();
%>

<%using (tabs.RenderHeader()) {%>
	<%using (tabs.Panes.RenderNextPane()) { %><p>Proin ...</p><%} %>
	<%using (tabs.Panes.RenderNextPane()) { %><p>Morbi ...</p><%} %>
	<%using (tabs.Panes.RenderNextPane()) { %><p>Mauris ...</p><%} %>
<%} %>
</asp:Content>



<asp:Content ID="Content5" ContentPlaceHolderID="DemoJavaScriptCodeContent" runat="server">
<%
	var tabs = Html.CreateTabs("tabs");
	this.Model.ConfigureTabs(tabs);
%>	
<%=this.Model.JavaScriptCode(tabs)%>
</asp:Content>

<asp:Content ID="Content6" ContentPlaceHolderID="DemoMethodsContent" runat="server">
	<ul class="horizontal">
		<li><button id="disableAll" title="Disables the tabs control (note this does not work - see jQuery UI issue #4386 http://bugs.jqueryui.com/ticket/4386) ">Disable All</button></li>
		<li><button id="enableAll" title="Enables the tabs control (note this does not work - see jQuery UI issue #4386 http://bugs.jqueryui.com/ticket/4386) ">Enable All</button></li>
		<li><button id="addTab" title="Adds a tab (note the 'beforeLoad' event won't fire until you click on the tab itself).">Add [dynamic] Tab</button></li>
		<li><button id="removeTab" title="Removes the first tab.">Remove (1st) Tab</button></li>
		<li><button id="startRotate" title="Starts automatic rotation of tabs.">Start Rotate</button></li>
		<li><button id="stopRotate" title="Stops automatic rotation of tabs.">Stop Rotate</button></li>
		<li><button id="widget" title="Shows the HTML for the .ui-tabs element.">Widget</button></li>
		<li><button id="destroy" title="Returns the tabs to it's pre-init state.">Destroy</button></li>
	</ul>
	<ul class="clear horizontal">
		<li><button id="selectTab-1" title="Select the first Tab.">Select Tab #1</button></li>
		<li><button id="enableTab-1" title="Enable the first [disabled] Tab.">Enable Tab #1</button></li>
		<li><button id="disableTab-1" title="Disable the first [enabled] Tab (selected tab cannot be disabled).">Disable Tab #1</button></li>
	</ul>
	<ul class="clear horizontal">
		<li><button id="selectTab-2" title="Select the second Tab.">Select Tab #2</button></li>
		<li><button id="enableTab-2" title="Enable the second [disabled] Tab.">Enable Tab #2</button></li>
		<li><button id="disableTab-2" title="Disable the second [enabled] Tab (selected tab cannot be disabled).">Disable Tab #2</button></li>
	</ul>
	<ul class="clear horizontal">
		<li><button id="selectTab-3" title="Select the third Tab.">Select Tab #3</button></li>
		<li><button id="enableTab-3" title="Enable the third [disabled] Tab.">Enable Tab #3</button></li>
		<li><button id="disableTab-3" title="Disable the third [enabled] Tab (selected tab cannot be disabled).">Disable Tab #3</button></li>
	</ul>
	<br />
	<br />
	<p>
		Note that in jQuery UI 1.9 the rotation of tabs has been 
		<a href="http://jqueryui.com/upgrade-guide/1.9/#removed-rotate-method">depreciated</a>.  
		There is however an <a href="https://github.com/cmcculloh/jQuery-UI-Tabs-Rotate">alternative plug-in</a> available
		(see <strong>tabs.js</strong> in the <strong>Scripts</strong> folder for implementation details).
	</p>
<%
	var tabs = Html.CreateTabs("tabs");
	this.Model.ConfigureTabs(tabs);
%>
	<script type="text/javascript">	
	$(document).ready(function() {
		$("#enableAll").click(function() { 
			alert("Note 'Enable All' does not work\n\nsee jQuery UI issue #4386 http://bugs.jqueryui.com/ticket/4386\n\nIt's present here for when it get's fixed."); 
			<%tabs.Methods.Enable();%>; 
		});
		$("#disableAll").click(function() { 
			alert("Note 'Disable All' does not work\n\nsee jQuery UI issue #4386 http://bugs.jqueryui.com/ticket/4386\n\nIt's present here for when it get's fixed."); 
			<%tabs.Methods.Disable();%>; 
		});
		$("#addTab").click(function() { addTab("New Tab", '<%=Url.Action("GetDynamicTab", "Builder")%>'); });
		$("#removeTab").click(function() { removeTab(0); });
		$("#startRotate").click(function() { startRotation(); });
		$("#stopRotate").click(function() { stopRotation(); });
		$("#widget").click(function() { alert( "Widget HTML:\n\n" + <%tabs.Methods.Widget();%>.html() ); });
		$("#destroy").click(function() {  if (confirm("are you sure you want to destroy the tabs control?")) <%tabs.Methods.Destroy();%>; });

		$("#selectTab-1").click(function() { <%tabs.Methods.SetActive(0);%>; });
		$("#selectTab-2").click(function() { <%tabs.Methods.SetActive(1);%>; });
		$("#selectTab-3").click(function() { <%tabs.Methods.SetActive(2);%>; });
		$("#enableTab-1").click(function() { <%tabs.Methods.Enable(0);%>; });
		$("#enableTab-2").click(function() { <%tabs.Methods.Enable(1);%>; });
		$("#enableTab-3").click(function() { <%tabs.Methods.Enable(2);%>; });
		$("#disableTab-1").click(function() { <%tabs.Methods.Disable(0);%>; });
		$("#disableTab-2").click(function() { <%tabs.Methods.Disable(1);%>; });
		$("#disableTab-3").click(function() { <%tabs.Methods.Disable(2);%>; });
	});
</script>
</asp:Content>

